version: '3'

services:
    db_mysql:
        image: mysql:latest
        volumes: 
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306

    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - db_mysql
        ports: 
            - "8000:8000"
        volumes: 
            - .:/app